# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"search_images_ddg": "scrape.ipynb",
         "download_and_save": "scrape.ipynb",
         "search_and_download": "scrape.ipynb",
         "Category": "scrape.ipynb",
         "img_scrape": "scrape.ipynb",
         "browse_images": "scrape.ipynb",
         "get_thumb_urls": "scrape.ipynb",
         "exhibit_urls": "scrape.ipynb",
         "softmax": "utils.ipynb",
         "calc_prob": "utils.ipynb",
         "one_hot": "utils.ipynb",
         "on_colab": "utils.ipynb",
         "TrianglePlot2D_MPL": "viz.ipynb",
         "setup_plotly": "viz.ipynb",
         "TrianglePlot3D_Plotly": "viz.ipynb",
         "plotly_already_setup": "viz.ipynb",
         "setup_bokeh": "viz.ipynb",
         "TrianglePlot2D_Bokeh": "viz.ipynb",
         "CDH_SAMPLE_URLS": "viz.ipynb",
         "bokeh_already_setup": "viz.ipynb",
         "VizPreds": "viz.ipynb",
         "image_and_bars": "viz.ipynb",
         "sorted_eig": "viz.ipynb",
         "pca_proj": "viz.ipynb"}

modules = ["scrape.py",
           "utils.py",
           "viz.py"]

doc_url = "https://drscotthawley.github.io/mrspuff/"

git_url = "https://github.com/drscotthawley/mrspuff/tree/master/"

def custom_doc_links(name): return None
