# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nimport": "nimport.ipynb",
         "fetch_image_urls": "scrape.ipynb",
         "download_and_save": "scrape.ipynb",
         "search_and_download": "scrape.ipynb",
         "Category": "scrape.ipynb",
         "img_scrape": "scrape.ipynb",
         "browse_images": "scrape.ipynb",
         "get_pca_xy": "scrape.ipynb",
         "plot_hover": "scrape.ipynb",
         "plot_triangle": "scrape.ipynb",
         "softmax": "utils.ipynb",
         "calc_prob": "utils.ipynb",
         "triangle3d_plotly": "viz.ipynb",
         "TrianglePlotBokeh": "viz.ipynb",
         "VizPreds": "viz.ipynb"}

modules = ["nimport.py",
           "scrape.py",
           "utils.py",
           "viz.py"]

doc_url = "https://drscotthawley.github.io/mrspuff/"

git_url = "https://github.com/drscotthawley/mrspuff/tree/master/"

def custom_doc_links(name): return None
